import { Poppins, Kdam_Thmor_Pro } from "next/font/google";

const kdamThmorPro = Kdam_Thmor_Pro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-kdam",
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins", // Define a CSS variable
  weight: ["300", "400", "500", "600", "700"], // Include necessary font weights
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${kdamThmorPro.variable}`}>
      <body>{children}</body>
    </html>
  );
}
