import "../globals.css";
import type { Metadata } from "next";
import { Navbar } from "@/components/common/layout/Navbar/Navbar";
import { SiteFooter } from "@/components/common/layout/Footer";

export const metadata: Metadata = {
  title: "psykick Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="bg-[#371B77]  ">{children}</div>

        <SiteFooter />
      </body>
    </html>
  );
}
